# -*- makefile -*-
## -----------------------------------------------------------------------
## Intent: Examples of command line argument parsing
## -----------------------------------------------------------------------

all:
	@echo
	@echo 'ARGV parsing with portable getopt command'
	./parse_args.sh --src 'foo' --dst 'bar' -- "extra_1" "extra_2"

	@echo
	@echo 'ARGV parsing w/o dependencies'
	./no_deps.sh --trace --int 5 --src /dev/null

# [EOF]
