# -*- makefile -*-
## -----------------------------------------------------------------------
## Intent: A template makefile with library includes and common targets.
## Hierarchy:
##    makefiles/ # {ONF_MK}
##    {project}/makefile
##    {project}/makefiles/
##    {project}/makefiles/include.mk
##    {project}/makefiles/lint/
##    {project}/makefiles/lint/include.mk
##    {project}/makefiles/lint/json.mk
##    {project}/makefiles/lint/shellcheck.mk
##    {project}/makefiles/lint/yaml.mk
## -----------------------------------------------------------------------

.DEFAULT_GOAL := all

##-------------------##
##---]  GLOBALS  [---##
##-------------------##
dot         ?= .

# Defines for library makefile lib path: ../makefiles
ONF_TOP     ?= $(dot)$(dot)
ONF_MK      ?= $(ONF_TOP)/makefiles# path to common makefiles

# Defines for local makefile lib path: ./makefiles/*
TOP         ?= .
ONF_MK	    ?= $(TOP)/makefiles

##-------------------##
##---]  TARGETS  [---##
##-------------------##
all:

## -----------------------------------------------------------------------
## -----------------------------------------------------------------------
build:
lint:
test:

## -----------------------------------------------------------------------
## -----------------------------------------------------------------------
clean ::
sterile ::

## -----------------------------------------------------------------------
## -----------------------------------------------------------------------
help ::
	@echo "Usage: make [options] [target] ..."

##--------------------##
##---]  INCLUDES  [---##
##--------------------##
include $(ONF_MK)/include.mk

#  [EOF]
